[package]
name = "rust-ipmi"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
bincode = "1.3.3"
bitvec = "1.0.1"
serde = { version = "1.0.192", features = ["derive"]}
hmac = "0.12.1"
sha2 = "0.10.8"
